In [19]:
import pandas as pd
import pickle as pk

In [26]:
games_df = pd.read_csv('Games.csv')
# city_name_Dict = pk.load(open('city_name.pickle'))
name_pref_Tuples = pk.load(open('name_pref.pickle'))

In [27]:
Team_Stat = {}
for team, pref in name_pref_Tuples:
    Team_Stat[team] = {'home_win':0, 'visit_win':0, 'W':0, 'home_lose':0, 'visit_lose':0, 'L':0}

In [28]:
for idx, row in games_df.iterrows():
    home = row['home_team']
    visit = row['visit_team']
    h_score = int(row['home_score'].split()[0]) # possible 'OT'
    v_score = int(row['visit_score'].split()[0])
    if h_score > v_score:
        Team_Stat[home]['home_win'] += 1
        Team_Stat[home]['W'] += 1
        Team_Stat[visit]['visit_lose'] += 1
        Team_Stat[visit]['L'] += 1
    else:
        Team_Stat[visit]['visit_win'] += 1
        Team_Stat[visit]['W'] += 1
        Team_Stat[home]['home_lose'] += 1
        Team_Stat[home]['L'] += 1

In [32]:
stat_df = pd.DataFrame(Team_Stat).T

In [36]:
stat_df.sort_values('W', ascending=False)

                         L   W  home_lose  home_win  visit_lose  visit_win
Golden State Warriors    9  73          2        39           7         34
San Antonio Spurs       15  67          1        40          14         27
Cleveland Cavaliers     25  57          8        33          17         24
Toronto Raptors         26  56          9        32          17         24
Oklahoma City Thunder   27  55          9        32          18         23
LA Clippers             29  53         12        29          17         24
Atlanta Hawks           34  48         14        27          20         21
Boston Celtics          34  48         13        28          21         20
Miami Heat              34  48         13        28          21         20
Charlotte Hornets       34  48         11        30          23         18
Indiana Pacers          37  45         15        26          22         19
Detroit Pistons         38  44         15        26          23         18
Portland Trail Blazers  38  44         13        28          25         16
Memphis Grizzlies       40  42         15        26          25         16
Dallas Mavericks        40  42         18        23          22         19
Chicago Bulls           40  42         15        26          25         16
Houston Rockets         41  41         18        23          23         18
Washington Wizards      41  41         19        22          22         19
Utah Jazz               42  40         17        24          25         16
Orlando Magic           47  35         18        23          29         12
Milwaukee Bucks         49  33         18        23          31         10
Sacramento Kings        49  33         23        18          26         15
Denver Nuggets          49  33         23        18          26         15
New York Knicks         50  32         23        18          27         14
New Orleans Pelicans    52  30         20        21          32          9
Minnesota Timberwolves  53  29         27        14          26         15
Phoenix Suns            59  23         27        14          32          9
Brooklyn Nets           61  21         27        14          34          7
Los Angeles Lakers      65  17         29        12          36          5
Philadelphia 76ers      72  10         34         7          38          3